name: reavaya_app
description: A new Flutter application
version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.0
  cupertino_icons: ^1.0.2
  flutter_paystack: ^1.0.7
  get: ^4.6.5
  http: ^0.13.5
  fluttertoast: ^8.2.2
  qr_flutter: ^4.1.0
  shared_preferences: ^2.2.0
  marquee: ^2.1.1
  qrscan: ^0.3.3
  permission_handler: ^10.4.3
  fl_chart: ^0.41.0
  flutter_slidable: ^0.6.0
  flutter_email_sender: ^6.0.1
  google_maps_flutter: ^2.2.0
  google_map_polyline_new: 0.3.0+2
  randomstring_dart: ^0.0.4
  intl: ^0.17.0
  flutter_polyline_points: ^1.0.0
  url_launcher: ^6.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/busIcon.jpg
